services:
  dragonwilds:
    image: andyaltsys/dragonwilds-dedicated-server:latest
    container_name: dragonwilds
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}/udp"
    env_file:
      - .env
    volumes:
    - ./server-data:/home/ubuntu/Steam
    restart: unless-stopped