services:
  dragonwilds:
    # build: .
    # stdin_open: true   # equivalent to docker run -i
    # tty: true          # equivalent to docker run -t

    image: andyaltsys/dragonwilds-dedicated-server:${IMAGE_TAG}
    container_name: "${CONTAINER_NAME}"
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}/udp"
    env_file:
      # - path: ./env.d/compose.env
      - path: ./env.d/container.env
      - path: ./env.d/server.env
      - path: ./env.d/overrides.env
        required: false
    volumes:
    - "${DATA_VOLUME}"
    - ./env.d/server.env:/config/server.env  # Mount for entrypoint to update
    restart: "${RESTART_POLICY}"
